{% extends 'partial-template.html' %}
{% block title %}404!{% endblock %}
{% block description %}This page doesn't seem to exist!{% endblock %}

{% block content %}
<div class="text">
Oops! You've stumbled across a missing page! If you think this page is supposed to exist, please <a href="mailto:webmaster@illandril.net">let me know by emailing webmaster@illandril.net</a> and I'll try to fix it ASAP.
<br>
Until then, feel free to take a look around the rest of my site.
</div>
{% endblock %}
