{% extends 'story-template.html' %}
{% block storyTitle %}Untitled (An End to the Peace, Part 4){% endblock %}

{% block story %}
        <!-- ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal -->
            <!-- ngIf: line.special --><div data-ng-if="line.special" class="notmine">The Juggernaut is a reference to a creature from Ultima Online. The references to Orcs and Elves are also most directly from Ultima Online, though they have been common in fantasy stories for much longer. The character Xaviel Tannon was created by another UO player, who collaborated with me with this story (he wrote a story at the same time going into details about what Xaviel did the time he is absent from this story). The "Knights" is a reference to the "Knights of Yew" guild in Ultima Online that Xaviel and I were a part of.</div><!-- end ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal -->
            <!-- ngIf: line.special --><div data-ng-if="line.special" class="authornote">Please forgive the complete lack of future mention about the ornate dagger. It was a plot device for things that went on within Ultima Online that I never wrote stories about (and don't remember enough details to write them now). Also, I think I did give this story a title at some point, but I can't remember it or find any reference to what I called it anywhere in my old files and notebooks.</div><!-- end ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You are going somewhere?" asked Karana.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh. Hello sis. I'm going with Arthur to find his friend. I planned on letting you know after I finished getting ready," replied Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"When are you leaving?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Tomorrow morning. After breakfast."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Is Arthur still having Aaril get him help from the Sincaal?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No. He's telling him we don't need the scout anymore right now, actually."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Are you sure you'll be able to find your way?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I don't think that was the scout's purpose. Arthur just needed someone to go with him to help with his spell casting."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Arthur is a scout as well then?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Not exactly. He's more of a scholar."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Well... make sure you stay safe."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Of course," replied Aralyn. "Would you mind letting Coromath know for me? After I finish here I'm going to return to meditate in the garden."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"What about dinner? Have you eaten already?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No. I'm just going to have some fruit from the garden."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Alright. I'll see you in the morning then."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal -->
            <!-- ngIf: line.special --><div data-ng-if="line.special" class="storyBreak">---</div><!-- end ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I have decided on when I am going to leave," said Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh good. I can finish briefing the scout then. When will you go?" replied Aaril.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Tomorrow morning."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"But that won't..."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I know," interrupted Arthur. " Aralyn is going to take the Sincaal's place."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"But... 'Lyn is not a scout. She has barely even been outside of the Hymlen Forest."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I never needed a scout. I needed a mage who could move undetected."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Not meaning to question your decisions... but I'm not sure Aralyn is fit for much exploration. Especially not past Vueshaal..."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"She is better for the task than I. Together I think we will be just fine."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Can I be of any more help before you go?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No. I'm just going to rest for the night... after I eat that is."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Pleasant dreams then." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal -->
            <!-- ngIf: line.special --><div data-ng-if="line.special" class="storyBreak">---</div><!-- end ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur and Aralyn both rose early the next morning and ventured to the central garden to meditate. There, they discussed a few plans of action, though neither was sure of what exactly they would have to do. Despite their uncertainties, they were both confident they would be able to find and save Xaviel, regardless of what lie in their way. After about an hour, they headed to the dining hall, where they met Coromath, Karana, and Yan'Chi.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Good morning to you all," greeted Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Kin I gu wid yoos missur Arder tu finez missur Xaveralls?" asked Yan'Chi.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No, I'm sorry child. I think you'd be much better off staying here," replied Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh... pleeeeze missur Arder?" persisted Yan'Chi.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Even if I thought you would be fine to come, I don't think your mother would appreciate me taking you away from her again."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Aww..." muttered Yan'Chi.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You are leaving right after you eat, correct?" questioned Coromath.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes, that is the plan," replied Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Are you sure you can handle the search alone?" asked Karana.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"With Aralyn by my side, I think we could take on the royal guard if we had to. Of course... I wouldn't dare try such a thing," smiled Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Well, I don't think you'll face that much trouble on the search, I suppose. Are you all prepared? Or have you more to get ready?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I'm not as well suited as I would like, but the time it would take to be any more prepared would not be worth the further risk of Xaviel's life," replied Arthur. "Nor do I think he would appreciate making him wait lost out there any further."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I'm as ready as I'll ever be... I think," answered Aralyn. "Oh. Can you watch Elaise for me? She should be fine on her own, but she has nearly tripped over the falls on a couple occasions. I don't want him to get hurt and remain untended to while I'm away."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Of course," replied Coromath.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Who is Elaise?" asked Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Didn't I introduce you to her? She is my pet Eilshif."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Eilshif?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«I'd'z like one a dem panther tingies in yer world missur Arder,» translated Yan'Chi.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Ah. I will have to meet her when we return."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Aaril walked into the room and greeted everyone. "I just spoke with Gerül. He says breakfast will be right out."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Good. I don't want to leave too late... not to mention, I'm starving," said Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The six exchanged conversation as they ate, and the pair said their farewells before leaving the castle. Arthur and Aralyn traveled at a steady pace from Hymlen to the swamplands, making it there just before midday. Before they passed through the swamp, they took a short break to have some fruit. For the most part, their trip from Hymlen to Vueshaal pass was quiet, both thinking to themselves as to what might lie ahead of them.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Stay close behind me. Much of the swamp has sink holes," said Arthur as the pair prepared to cross the swamp. "If what Aaril told me was correct, we shouldn't run into any trouble before we get to the mountain."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The swamps stretched further than expected, but there was no trouble to be seen. As they reached Vueshaal pass, they each lit a torch and headed inward.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Aaril said the Sincaal marked the forks both ways to get through these tunnels. He also said the Darshin seem to be too frightened now to pass the shallows on the other side of the island, so we shouldn't have to worry about anything more then cave critters."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"The cave has a crude smell to it. Anything that would stay in here would probably stay too deep to bother us," Aralyn pointed out.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Right. We should be on the other side just past nightfall anyhow."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The marks in the caves were clearly visible, and the pair got through the tunnels with no problems. They set up a camp close to the mountain after they exited the caves. After the camp was set up, they had a small meal and prepared to rest.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Something was following us at the end," said Arthur as he unrolled his bedroll.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You noticed it too then? I had thought I was just imagining something."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Aye. It wasn't hostile, though. Whatever it was, it is just trying to follow us it seems."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Keep an eye open as you sleep just to be safe, but I don't think it had unfriendly intentions either."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Pleasant dreams." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal -->
            <!-- ngIf: line.special --><div data-ng-if="line.special" class="storyBreak">---</div><!-- end ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Two hours after Arthur and Aralyn left the castle, a Hymlen city guard rushed into the castle.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Zi'Guiel! Where is the king?" asked the guard.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I last saw him heading to the library," replied the royal guard.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Thank you," said the guard, and he ran off to the library.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"What's the rush, lieutenant?" asked Coromath as the guard ran into the library.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Sir... It's Yan'Chi... She has run off."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Well why aren't you out stopping her?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"She... she disappeared when I tried sir. In the middle of the road, without any incantation."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Trying to catch up with Arthur and 'Lyn no doubt. I guess she mastered her robes while she was gone..."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Robes, sir?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes. She has robes that let her blend in with her surroundings. It's a mental incantation to activate them, not spoken tongue. You may return to your post. I will handle this from here."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes sir."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The guard left to his post, and Coromath went to find Aaril and Karana. He gathered the two in the throne room and told them of the problem.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You said that she was still having problems with her clothing when we sent her off, so I suppose Arthur had figured out the clothing and finished her training with it. What should we do about her disappearance?" asked Coromath.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"The only problem will be catching up with her. There is a spell that will allow us to see the clothing in its original color," replied Aaril.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Let her be," said Karana. Aaril and Coromath looked at her with shock. "She has enough Sincaal blood to find her way, and she obviously has enough talent to remain safe. She can run as fast as you, Coromath, so she should be in their care soon enough anyway. I was almost going to let her go anyway. She has great feelings for that Xaviel. He is like a big brother to her."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Very well. Mothers intuition never fails, after all," replied Coromath.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal -->
            <!-- ngIf: line.special --><div data-ng-if="line.special" class="storyBreak">---</div><!-- end ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur and Aralyn awoke early the next morning, and discussed their plans as they ate breakfast.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"There's no need to worry about what was following us anymore," said Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No. She sneezed last night."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"She?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yan'Chi." As he spoke the child's name, Aralyn started to look around. "No need to look. You won't be able to see her until she shows herself. She's wearing her magical robes. She can blend in to whatever she wants."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"We'll just let her follow us then?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Well... where are we headed next?" asked Aralyn as she looked out past the shallows that split Vueshaal and the continent of the Darshin, and whatever else might dwell on it.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"We will cross the shallows, and then shape shift on the other side. There, we'll turn eastward, staying in site of the mountain and the shore as long as we can. From there, I don't know just yet."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Very well. Let's get leaving quickly. We don't want to take any longer than we have to."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The pair finished breakfast and picked up camp. As they started off across the shallows, Aralyn looked behind herself a little, scanning for Yan'Chi. The water remained shallower than the pair's boots through the center of it, almost as if it had once been filled in to act as a path, but had since been slightly eroded away. After they reached the other side, they could faintly hear the water sloshing around on the Vueshaal shore.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"There seem to be many of those creatures walking about," said Arthur as he pointed to a jaguar-like animal. "From here it looks like the area is mostly jungle and mountain."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes. I think it would be best to move as those beings, the Kryün."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"They both cast their polymorphing spells and transformed themselves into Kyrün. As the pair headed east and slightly south, they could see the water behind them slowly moving as Yan'Chi moved through it.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Will she be able to follow us in this form?" asked Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I have never been able to hide from her."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Alright. Hopefully the Darshin will pay us no heed, should we run into any."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The two walked through the thin jungle, leaves occasionally being rustled by their hidden follower. They passed only a handful of Darshin before midday, but they saw signs of a great city within the mountains to the south. For lunch, they ate some of the fruit growing within the jungle. Shortly before nightfall, the pair reached a secure clearing, where they set up camp after returning to their normal forms.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The two conversed after setting up the camp.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You have adapted quite well to our world. Even as we search into areas that even I have not seen before you seem comfortable with your surroundings," Aralyn said to Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes, I suppose. I guess I've always found it easy to get used to new environments. It comes from my frequent lengthy wanderings in my home world, I would imagine," replied Arthur. </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No... It's more than that... almost like you feel at home. Is Erath that much like the world you come from?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Not really, but now that you put it that way... I do feel more comfortable in this world. I can't say I've ever felt at home anywhere, however." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Never? I can understand feeling displaced when you wander... but you've never had a place to call home? Not even as a child?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"My childhood was even worse than now, in that regards. At least now I feel like I'm part of a family... with the Knights that is."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"The 'Knights'? You mean the group of your friend that we are searching for, um... Xaviel is it? The group he is a part of?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Aye. They are like family to me. Well... more like family than anyone else I've known." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"What about your parents?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I never met them. Well... not my biological ones at least. I was abandoned, then found and raised by half-elves." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"'Half-elves'?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh, right. I sometimes forget that you don't really know anything of my world. A half-elf is a being that is a mix between elf, my race, and human, a race much like your people." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You didn't see your adopting parents as family?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No. I never felt like I belonged with them. Physically they weren't that different than me... but I could never accept them as family." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You must've had a hard childhood..." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I would've, if it weren't for Gildar and the forest animals near my home." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"What do you mean?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"They were my only friends. For sixteen years my best friends were forest critters. When I was 16 years old, I met Gildar, who is now a fellow Knight of Xaviel, and we have been friends since." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Well, I suppose that's not too bad." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"No, not really. I think I would've liked growing up in Hymlen better though." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"She really is a wonderful city..." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes, yes she is. But that is not why I'd rather have grown up there." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh?" </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I would've been able to meet you earlier in my life," said Arthur, causing Aralyn to blush slightly. "We've only known each other for a week, and I already feel closer to you than anyone else I've known." </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Aralyn smiled and turned her head slightly away, and then suggested, "We have yet to eat. Let's have some dinner."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The two ate their dinner rations, and went to sleep. The next morning, they turned southward, following the mountains a little closer then the shore. Before leaving the camp, they returned to Kryün form. All was quiet before lunch, which they ate in a small clearing shortly before noon. After lunch, they began to turn more eastward. A short distance from where they ate, Arthur caught glimpse of a body lying up against a tree.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Look over there," said Arthur as he pointed to the body.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh my!" Aralyn stepped towards the corpse, so as to see what it was. "A Darshin was felled. As well as two others creatures!"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur approached Aralyn so he could see the other two. "What are they?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I... I believe they are Sishai... though we have not seen of their race since well before my birth."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur studied the area briefly, and then returned to his elvish form. "We shouldn't stay here long, but I want to get a look at these beings while I have the chance."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur first examined the Darshin. He noticed that its skin was thick, like an ogre's, yet it's muscles were built for a good balance of speed and strength, much like an orc's. The two Sishai were unlike anything he had seen before. Their faces were clean flesh, but the rest of their bodies were covered in a thin layer of dirty blond fur. They looked to be swift creatures, but not very strong. Both of their faces were painted in elaborate designs with dark ink, and a hexagonal shape separate from the rest of the paint in the center of their forehead. On closer examination, Arthur realized that the figures in their foreheads were obsidian crystals infused in their skin.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Look here... they have crystals in their foreheads."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Odd... I don't remember hearing about that before..."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Shh..." paused Arthur as he turned his ears to listen. "Did you hear that?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Hear... what?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Never mind. Let's continue on," suggested Arthur before he returned to Kryün form.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The two continued on with their search for Xaviel. They reached a small glade just as the sun began to fall behind the trees, and decided to stop for the night.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Is she still following us?" quietly asked Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes. She climbed up that tree behind me while we laid out our bedrolls."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Good. I'd hate for her to get lost out here."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I don't think we'll have to worry about that."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The sun fell and the moon rose. Another day had past with no sign of the missing Knight. The next morning, the pair continued eastward, again taking the shape of the Kryün. They traveled eastward for slightly more than an hour, when they caught sight of a recent battleground.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"There must be at least fifty of them!" exclaimed Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Yes, and the site is..." Arthur began, pausing slightly for a quiet gasp from behind him. "The site is fresh. Maybe a day or two old. We should be getting close."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I hope so. I do not wish to be in these lands any longer than I must. There is far too much death about."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Indeed." Arthur closed his eyes as he returned to his elvish form. "Help me search the area for tracks."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Aralyn nodded before she returned to her Erathi form, then looked around the field. In one corner of the field, Arthur paused to pick something up from aside a corpse.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"What is it?" questioned Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"An ornate dagger. Magical of some sort I believe." Arthur pocketed the dagger before he went back to looking around.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Look here!" called Aralyn. "They have odd creatures amongst them."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur walked to Aralyn to see the beings. "Orcs. They are nothing to worry about if any more are around. They're like a weak form of your Darshin. It is rather odd that they are with this group, though."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Interesting."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur found some tracks in the southeast corner of the battle site. "Over here! He ran off this way."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur and Aralyn followed the tracks, retaining their natural forms. After about two minutes of walking, a second set of tracks met the ones they were following, and the ground was disturbed, as if there were a long battle between the two.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«A Juggernaut...» muttered Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"A what?" questioned Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Hm? Oh. Nothing." Arthur pointed to the heavily armored body felled in front of them. "One of the more elite troops. Hopefully he was the only one... Let's continue. Xaviel limped off this way," said Arthur as he turned north slightly. After ten minutes of walking, they reached a small glade. In the glade was the missing Knight, leaning against a tree.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Oh my! He is not in good shape at all!" exclaimed Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"He is badly wounded... and I don't think his wounds stop on the physical body," stated Arthur. Just as he finished speaking, Yan'Chi ran out from behind him and dropped to her knees beside Xaviel, sobbing quietly.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"They are good friends?" asked Aralyn quietly.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"He is like a brother to her."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Xaviel opened his eyes slightly and smiled at Yan'Chi. «Don't cry, child,» he said, before coughing a few times. «Everything will be fine,» consoled Xaviel, before closing his eyes again.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Help me heal his wounds," said Arthur to Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Aralyn nodded in response.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">They both stood on either side of Yan'Chi as they chanted spells of healing. A soft blue glow emanated from around Xaviel as the spells were cast. A look of contentment now shone on both of their faces, but worry obviously still overwhelmed them.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Let's hurry back to last eve's camp. We know it should be safe enough to rest there," suggested Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Good idea. I wouldn't want to run into anything while protecting a wounded, and shifting will no longer do us any good, unfortunately," replied Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur and Aralyn carried Xaviel as carefully and quickly as possible back to the glade they slept in the night before. Yan'Chi followed closely behind, her head looking down as she walked.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Don't fret too much, Yan'Chi," consoled Arthur, never actually looking back to see the child. "He will recover with time."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The group arrived at the glade with a good hour or two before the sun would fall behind the trees. Arthur took a quick look around the glade as Aralyn and Yan'Chi tended to the wounded Knight's injuries some more.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding"> "The area is clear," said Arthur. "Except for a few scavengers picking at the corpses at the battlefield."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"That is good, at least. We may not be moving for the next day or two, unless we risk straining our backs too much."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"He usually recovers quicker than one would believe. He may very well be mobile by the morn."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"We shall see. Until then, however, we should let him rest," suggested Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur, Aralyn, and Yan'Chi shared a meal of dried fish steaks and fruit. Arthur finished quickly and gathered wood for a small fire.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"We'll probably want to keep an eye open tonight, just to be safe," said Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"We should check around the area once more before it gets dark."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"That's a good idea."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Xaviel blinked open his eyes, and strained out a few words, «Finally learned their language, eh?»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Replying in his common tongue, Arthur said, «Yes, yes I did. Would've been out here earlier for you if I wouldn't have needed help to do so.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Yan'Chi ran up and hugged Xaviel, «Xaverallz!»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Xaviel returned the hug softly, «Not that good yet, child. Don't be hugging me too hard now,» grinned Xaviel.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Think you might be good to travel tomorrow?»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Not without a little help, I don't think. But we don't have much distance to travel, unless you've carried me farther then I think.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«What do you mean? It's at least three days of travel to Hymlen.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«There is a closer city we can go to. Them furry telepathic savages offered me passage before. Their ships are only half a day from where I was attacked.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Really?»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«What is he saying, Arthur?» asked Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Sorry. Forgot that you couldn't understand us. He says some creatures, the Sishai I think, had offered him passage to a closer Erathi city, although passage would be by ship."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Enshala, of course. The total distance would be longer, but we could travel by wagon to Hymlen."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«You will have to lead us to them, Xaviel, but your idea is a good one.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Let's continue in the morning, I need some rest.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Of course. Pleasant dreams.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur turned and chatted with Aralyn and Yan'Chi quietly as Xaviel slept. After a while, Aralyn and Yan'Chi went to sleep, and Arthur went on a quick patrol around the area before he joined them. They awoke with the sun, and planned their trip.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«We go that way,» instructed Xaviel, still sitting against the tree.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«I don't think so. That would lead us straight to the Darshin.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«You sure?»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Positive.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Then it has to be... that way.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«That would turn us away from the Erathi mainland.»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Well then where are we?»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Here... I'll draw a map of what I know,» said Arthur. Arthur looked up to the sky, and then turned north. In the upper left of his map, he drew Hymlen, the lower edge of the Erathi Mountains, and the swamp. Below the swamp, he added Vueshaal pass, and the upper left of the continent they were on. He continued to the right of that, partially guessing on the coastline, but placing the right edge of the Darshin Mountains, the battlefield, and where they found Xaviel as precisely as he could.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Enshala would be about here," said Aralyn, Marking and area right of Vueshaal.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«That's where the city is,» translated Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Then the savages should be over that way then,» said Xaviel, pointing northeast.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">They traveled surprisingly fast, considering the wounds Xaviel carried, and made it to a Sishai settlement shortly after noon. As they arrived, Xaviel stumbled in front of the group and was greeted in his mind, «*So the warrior returns. He brings with him friend or foe?*»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«"They are friends. We need that passage you mentioned to me earlier,"» responded Xaviel, speaking aloud.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«*Very well. Come with me. I shall sail you across.*»</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«This way.» Xaviel gestured to the others, following the Sishai who had greeted him.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The passage to the Erathi mainland was quiet, and they arrived at dusk. The Sishai left them just outside of Enshala, and turned back home right after they got on shore.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Come, there is a tavern near the edge of town who knows my family well," said Aralyn. "We can stay there tonight, then get back to Hymlen tomorrow."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The rest followed without question, all of them tired from their travels. After a short explanation from Aralyn, the innkeeper showed the group to a large room. Even though their day had been quiet, they were all exhausted and fell sound asleep the moment they lay down on their beds. As morning came, they all felt rejuvenated, except for Xaviel, whom was still suffering from the impact of his wounds. As the Knight tried to walk, he found that he was forced to limping.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Here... let me ease your wounds," said Aralyn. She softly incanted her spell and held her palms to his left leg. When she finished the incantation, a soft blue glow once again surrounded Xaviel's wounds.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«No clue what you just said, but thanks. Should help me move around,» replied Xaviel.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur translated for Aralyn who smiled a 'You're welcome' in return.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Lets get some breakfast, then find us a wagon,» said Arthur to Xaviel and Yan'Chi before repeating himself in Erathi for Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">As they were leaving the inn, the innkeeper stopped them. "You won't leave without breakfast, will you?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"We didn't realize you were equipped to supply breakfast," replied Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"The selection is limited, but the food is delicious."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Very well then. We will wait in the other room. Just bring us as much a variety as you can with enough for all of us."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"It should not take long."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Our thanks."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The group sat at a table in what they now realized was a rather large dining hall. The food they were brought included an assortment of fruit, sausage-like meat patties, and a pastry-like product that had a mix of a pancake and biscuit like crust, with a mixed fruit blend filling.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«That was the best meal I've had in a while,» said Xaviel as he finished his last bite.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">«Indeed, that was a rather good meal,» replied Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"We should get going if everyone is all done," suggested Aralyn.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Ya ya," replied Yan'Chi, before licking the remaining filling off her fingers.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Let's find a wagon," replied Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The group got up and left the hall. Before they left the inn, Aralyn addressed the innkeeper, "Many thanks for the food. It was delicious."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You're welcome, M'lady. Is there anything else I may do for you?"</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Not unless you know of someone who has a spare wagon we could use."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You may use mine if you wish. I only use it when the inn is closed anyhow."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"That is quite generous of you Kyl'Shee. I will be sure to send it back with some payment for your services as soon as I can."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Think nothing of it. I'll bring my holshee around for you. The wagon is on the side of the building."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The group went outside and waited for the holshee, a pair of horse-like creature. Kyl'Shee hooked up the holshee and bid them farewell, "Safe travels my ladies and company." Looking to Yan'Chi, he added, "Send my greetings to your mother and father for me."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Ya ya missur."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The group went on the rather uneventful trip to Hymlen from Enshala. The trip took less time than they had expected, and arrived in Hymlen shortly after noon. As they entered the castle, Karana greeted them emphatically. The queen rushed up and hugged her daughter, then looked up and welcomed the rest of the group back.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I was worried sick the entire time you were gone. It's good to see your faces again," said Karana.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"It was a frightening trip, but rather quiet, luckily," replied Aralyn. "Xaviel, unfortunately, is not in the best of shapes."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"Missur Kilesee sayz to tell yooz 'hi'," added Yan'Chi.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You... were in Enshala? It was a little out of the way, was it not?" questioned Coromath.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"It was a faster choice under the circumstances. I'll tell you of it a little later, but I think first we should get Xaviel looked at, and send Kyl'Shee's wagon back, along with some compensation for allowing us to stay the night and eat breakfast in his inn."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">The next few weeks went along in a consistent manner. Xaviel was mostly stuck in bed, watched over mostly by Arthur and Aralyn. Physically, he recovered quickly and completely, but his mind was plagued with twisted thoughts. Xaviel often woke from nightmares, and no one could fully explain what was the cause of his ailment. After a while, Arthur decided it would be best to send Xaviel home so the Knights could take care of him.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"I don't really want to leave here, but for Xav's sake, I'm afraid I must. I'll come back though, once I can be confident he will recover," said Arthur.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">"You'll have a place to stay, regardless of when you come back," said Aralyn. She paused a moment before adding, "I'll miss you..."</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Arthur smiled for a moment and gave Aralyn a hug before leaving to where Xaviel and Aaril were waiting. </div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal -->
            <!-- ngIf: line.special --><div data-ng-if="line.special" class="storyBreak">---</div><!-- end ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines --><div data-ng-repeat="line in lines" class="ng-scope">
            <!-- ngIf: line.normal --><div data-ng-if="line.normal" class="storyLine ng-scope ng-binding">Weeks passed before Arthur returned, during which Yan'Chi worried about Xaviel's health, and Aralyn longed for Arthur's return.</div><!-- end ngIf: line.normal -->
            <!-- ngIf: line.special -->
        </div><!-- end ngRepeat: line in lines -->
{% endblock %}